apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustom-
namespace: public

commonLabels:
  app: webpage
  team: devops
  version: 1.1.7

commonAnnotations:
  note: "This is a stage deployment"

resources:
  - ns.yaml
  - ../../base

# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesstrategicmerge/
patchesStrategicMerge:
  - deploy-strategic-patch.yaml

# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
# https://fabianlee.org/2022/04/15/kubernetes-kustomize-transformations-with-patchesjson6902/
patches:
  # In-line patch
  - target:
      kind: Service
      name: svc-webpage
    patch: |-
      - op: add
        path: /spec/type
        value: ClusterIP
  # yaml file patch
  - target:
      kind: Service
    path: svc-patch.yaml
  - target:
      kind: VirtualService
    path: vs-patch.yaml

# Image patch
images:
  - name: kustomize-defined
    newName: cachac/kubelabs_webapp
    newTag: 1.1.7
