apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: default
rules:
  - apiGroups:
      [
        "",
        "apps",
        "autoscaling",
        "batch",
        "certificates.k8s.io",
        "extensions",
        "networking.k8s.io",
        "storage.k8s.io",
        "policy",
      ]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer-ns

rules:
  - apiGroups: [""]
    resources: ["namespaces", "nodes"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developer-ns
subjects:
  - kind: Group
    name: developer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: developer-ns
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer
subjects:
  - kind: Group
    name: developer
    namespace: kube-system
  - kind: Group
    name: developer
    namespace: istio-system
  - kind: Group
    name: developer
    namespace: flux-system
  - kind: Group
    name: developer
    namespace: karpenter

