apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-webpage-config
  
data:
  CONFIG_JS: |
    var config = (() => {
    return {
      API: "http://api.cachac.vendoamigos.com/graphql",
      WEBSOCKET: "ws://websocket.cachac.vendoamigos.com/graphql",
    };
    })();
